(function() {

    // Add smooth scrolling to all links
    $("a").on('click', function(event) {

        // Make sure this.hash has a value before overriding default behavior
        if (this.hash !== "") {
            // Prevent default anchor click behavior
            event.preventDefault();

            // Store hash
            var hash = this.hash;

            // Using jQuery's animate() method to add smooth page scroll
            // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
            $('html, body').animate({
                scrollTop: $(hash).offset().top
            }, 800, function() {

                // Add hash (#) to URL when done scrolling (default click behavior)
                window.location.hash = hash;
            });
        } // End if
    });


    // Email JS (contact form)
    // Code generated by email JS https://www.emailjs.com/
    emailjs.init("user_3NB50omIWwpQToXY0ergt");

    var myform = $("form#myform");
    myform.submit(function(event) {
        event.preventDefault();

        var params = myform.serializeArray().reduce(function(obj, item) {
            obj[item.name] = item.value;
            return obj;
        }, {});

        // Change to your service ID, or keep using the default service
        var service_id = "tsusmita_ymail_com";
        var template_id = "gscode_template";

        myform.find("button").text("Sending...");
        emailjs.send(service_id, template_id, params)
            .then(function() {

                alert("Hey there, I will contact you soon!");
                myform.find("button").html("Send Message<i class='fab fa-telegram-plane'></i>");
            }, function(err) {

                alert("Something went wrong!");
                console.log("Send email failed!\r\n Response:\n " + JSON.stringify(err));
                myform.find("button").text("Send");
            });
        return false;
    });


})();